Issue 84 column swap
FelixBaensch/MORTAR pull request #99
Opened 2024-04-25 12:49 UTC by JonasSchaub

- swapped positions of sample parent structure and sample parent name columns in fragments table
- added text wrap to sample parent name column
- tweaked magic number for pref width in molecules tab a bit to get rid of the unnecessary scroll bars
- abbreviated some column header labels in the fragments tab and added tooltips with the un-abbreviated labels to those headers that did not have one yet

2024-04-25 12:50 UTC, JonasSchaub commented
The exported PDF and CSV files did not have to be updated as described in the issue because they do not contain the sample parents or their names.

2024-04-25 12:52 UTC, JonasSchaub commented
@FelixBaensch could you maybe inspect the visual changes in the GUI and let me know what you think?

2024-04-25 14:13 UTC, FelixBaensch requested changes
I find the new arrangement takes a bit of getting used to. Maybe it looks better if the SMILES column is in front of the structure columns. 
And the heading "S. P. Name" is really odd.

2024-04-25 14:13 UTC, FelixBaensch commented on src/main/resources/de/unijena/cheminf/mortar/message/Message_en_GB.properties
> +MainTabPane.fragmentsTab.tableView.parentMolNameColumn.header = S. P. Name
S. P. Name is somehow odd and I don't like it.

2024-04-25 14:28 UTC, JonasSchaub commented
> I find the new arrangement takes a bit of getting used to. Maybe it looks better if the SMILES column is in front of the structure columns.

Hm, I don't know. I think the most important thing here are the fragment structures. And textual column in front that is not a name/ID is also odd, IMHO.

![image](https://github.com/FelixBaensch/MORTAR/assets/44881147/ac219f62-428b-4f07-b13a-03767d696104)

2024-04-25 14:29 UTC, JonasSchaub commented
> S. P. Name is somehow odd and I don't like it.

Do you have alternative suggestions, maybe? There is not a lot space available in the header and I don't like the header labels being abbreviated in the default size.

2024-04-26 05:04 UTC, FelixBaensch commented
> Hm, I don't know. I think the most important thing here are the fragment structures. And textual column in front that is not a name/ID is also odd, IMHO.

I fully agree that the most important thing is the fragment structure, but it's more pleasing to my eye this way. We could get Achim's professional opinion.

2024-04-26 05:31 UTC, FelixBaensch commented
> Do you have alternative suggestions, maybe? There is not a lot space available in the header and I don't like the header labels being abbreviated in the default size.

No, not really. How about just omitting the "Sample" and only mentioning in the tool tip and tutorial that there are several? And swap the "parent" for something like "source" or "root"?

2024-04-29 14:24 UTC, JonasSchaub commented
> We could get Achim's professional opinion.

I've e-mailed him with you in Cc.

2024-04-29 16:32 UTC, FelixBaensch commented
I like Achim's suggestion ;D

By the way, the arrangement of the columns can be customized by the user during a session. It is just not persisted.

2024-04-30 08:19 UTC, JonasSchaub commented
> By the way, the arrangement of the columns can be customized by the user during a session. It is just not persisted.

Ah wow, I did not know that, thanks!

2024-04-30 09:16 UTC, JonasSchaub commented
The new fragments tab arrangement:

![image](https://github.com/FelixBaensch/MORTAR/assets/44881147/6b7977c4-4b22-480c-90ff-796dba89e05e)

@FelixBaensch do you like it?

2024-04-30 11:33 UTC, FelixBaensch commented
> @FelixBaensch do you like it?

Since it pretty much implements my suggestions, yes!

2024-04-30 11:39 UTC, FelixBaensch approved these changes
Merge at will

2024-04-30 11:46 UTC, merged